### ISSUE TITLE
CARLA is not saving data  through the whole run correctly

### ISSUE THREAD

**Issue by OnePointOh** [EthanVeselka/E2E_Pseudo-Lidar#6]
Currently, when we are saving data to disk, only about the 1/3 of the simulation cameras gets saved, then only the depth maps are being saved. Figure out how to ensure all the data gets saved through the full run.

**Comment by OnePointOh** [comment]
potentially relevant https://github.com/carla-simulator/carla/issues/1224

**Comment by OnePointOh** [comment]
this might be solution https://carlasimblog.wordpress.com/2023/10/18/computer-queues-and-their-use-in-carla-simulator-to-render-large-images-without-image-drops/

**Comment by Fredy-Medawar** [comment]
Bounding boxes are sometimes not saved in the last couple of frames but marking solved for now.
